version: "3.7"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: yum_food
      POSTGRES_USER: yum_food
      POSTGRES_PASSWORD: password
      DB_EXTENSION: uuid-ossp
    ports:
      - "5432:5432"
    networks:
      - yum-network

  server:
    image: node:17
    command: sh -c "npm i && node src"
    ports:
      - 3333:3333
    working_dir: /app
    volumes:
      - ./server:/app
    networks:
      - yum-network

  client:
    image: node:17
    command: sh -c "npm i && npm run webpack && node index.js"
    ports:
      - 4444:4444
    working_dir: /client
    volumes:
      - ./client:/client
    networks:
      - yum-network

networks:
  yum-network:
    driver: bridge